#spring:
#  cloud:
#    stream:
#      bindings:
#        input:
#          destination: queue.log.messages
#          binder: local_rabbit
#          group: logMessageConsumers
#        output:
#          destination: queue.pretty.log.messages
#          binder: local_rabbit
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 192.168.0.172
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /
#server:
#  port: 0
#management:
#  health:
#    binders:
#       enabled: true


spring:
  cloud:
    stream:
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.0.172
                port: 5672
                username: guest
                password: guest
                virtual-host: /
      bindings:
        input1:
          destination: exchange-ramos1
          group: queue1
          binder: local_rabbit
        input2:
          destination: exchange-ramos1
          group: queue2
          binder: local_rabbit
        output1:
          destination: exchange-ramos1
          binder: local_rabbit
        output2:
          destination: exchange-ramos2
          binder: local_rabbit

        # WSO2 topic
        TXN_TOPIC_INPUT:
          destination: psl_demo
          group: queue13
          consumer:
            auto-bind-dlq: true
            republishToDlq: true
            maxAttempts: 5
          binder: local_rabbit
        TXN_TOPIC_OUTPUT:
          destination: psl_demo
          binder: local_rabbit

      rabbit:
        bindings:
#          input1:
#            consumer:
#              bindingRoutingKey: bindKey1
#          input2:
#            consumer:
#              bindingRoutingKey: bindKey2
          output1:
            producer:
              exchange-type: topic
          output2:
            producer:
              exchange-type: direct
#              routing-key-expression: "'bindKey2'"
#        default:
#          consumer:
#            bindingRoutingKey: default-queue
#          producer:
#            exchangeType: direct


# ************* WSO2_Dummy Application.properties ************
#spring:
#  cloud:
#    stream:
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: 192.168.0.172
#                port: 5672
#                username: guest
#                password: guest
#                virtual-host: /
#              listener:
#                direct:
#                  acknowledge-mode: MANUAL
#                simple:
#                  retry:
#                    enabled: true
#              template:
#                retry:
#                  enabled: true
#                receive-timeout: 5000
#      bindings:
#        TXN_TOPIC_INPUT:
#          destination: psl_demo
#          group: queue13
#          consumer:
#            auto-bind-dlq: true
#            republishToDlq: true
#            maxAttempts: 5
#          binder: local_rabbit
#
#        TXN_TOPIC_OUTPUT:
#          destination: psl_demo
#          binder: local_rabbit
